name: Expo Build and GitHub Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install
          npm install -g eas-cli

      - name: Authenticate with Expo
        run: eas login --token ${{ secrets.EXPO_TOKEN }}

      - name: Start Expo build (Android)
        run: eas build --platform android --profile release-apk

      - name: Wait for Expo build to finish
        run: |
          BUILD_ID=$(eas build:list --platform android --limit 1 --json | jq -r '.[0].id')
          echo "Waiting for Expo build to finish..."
          while true; do
            BUILD_STATUS=$(eas build:status --id $BUILD_ID --json | jq -r '.status')
            if [[ "$BUILD_STATUS" == "finished" ]]; then
              echo "Build finished."
              break
            fi
            sleep 10
          done

      - name: Get build artifacts
        run: |
          APK_URL=$(eas build:status --id $BUILD_ID --json | jq -r '.artifacts.buildUrl')
          echo "APK URL: $APK_URL"
          curl -L "$APK_URL" -o release.apk

      - name: Create GitHub Release and upload APK
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: "Automated release from Expo build"
          files: release.apk